FROM node:latest

ENV GITHUB_TOKEN=

RUN apt-get update && apt-get install -y git

WORKDIR /app

RUN git clone https://${GITHUB_TOKEN}@github.com/Joris07/cowaf.git

WORKDIR /app/cowaf

RUN npm install

EXPOSE 8080