version: '0'
name: cowaf

services:
  vuejs-app:
    build:
      context: .
      dockerfile: Dockerfile-vuejs
    container_name: vuejs-app
    working_dir: /app/cowaf
    ports:
      - "40110:40110"
    command: "npm run dev -- --host 0.0.0.0 --port 40110"

  symfony-api:
    image: php:8.2-apache
    build:
      context: .
      dockerfile: Dockerfile-symfony
    container_name: symfony-api
    ports:
      - "40111:81"

  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: xBcGNI29hyaTjdhk365GgX
      MYSQL_DATABASE: cowaf
      MYSQL_USER: cowafUser
      MYSQL_PASSWORD: w8yh9QLt5ibbcTN6xBXaj1
    ports:
      - "40112:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_ARBITRARY: 1
    ports:
      - "40113:80"
    depends_on:
      - mysql-db